[RP] Workarond for python error
ImportError: Failed to import _strptime because the import lockis held by another thread

Signed-off-by: Przemo Firszt <przemo@firszt.eu>